#!/bin/bash

DOCKERHUB_USERNAME="nagagogulan"
REPOSITORY_NAME="task"

# Log in to Docker Hub
docker login -u $DOCKERHUB_USERNAME

# Build and push new images
for tag in v1 v2 v3; do
    image_tag="${DOCKERHUB_USERNAME}/${REPOSITORY_NAME}:${tag}"
    
    # Build your Docker image (replace this with your actual build command)
    docker build -t $image_tag .

    # Push the Docker image
    docker push $image_tag
done

# Delete old images (example: keep the last 2 images)
image_tags_to_keep="v1 v2 v3"  # specify the tags you want to keep
existing_images=$(docker images ${DOCKERHUB_USERNAME}/${REPOSITORY_NAME} --format "{{.Tag}}")

for existing_tag in $existing_images; do
    if [[ ! " $image_tags_to_keep " =~ " $existing_tag " ]]; then
        docker image rm ${DOCKERHUB_USERNAME}/${REPOSITORY_NAME}:${existing_tag}
    fi
done

# Log out from Docker Hub
docker logout

