name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Choose the appropriate Node.js version

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: nagagogulan
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .github/workflows
        push: true
        tags: nagagogulan/node1:latest

    - name: Delete containers older than a week
      uses: snok/container-retention-policy@v2
      with:
          image-names: docker-debian-bullseye-min-stage1
          cut-off: A week ago UTC
          account-type: org
          org-name: rubyonracetracks
          keep-at-least: 1
          untagged-only: true
          token: ${{ secrets.SPECIAL_TOKEN }}
      if: ${{ github.ref == 'refs/heads/main' }}

    - name: Log out of the Docker container registry
      run: docker logout ghcr.io
      if: ${{ github.ref == 'refs/heads/main' }}
