name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Choose the appropriate Node.js version

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: nagagogulan
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image with unique version tag
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: .github/workflows
        push: true
        tags: |
          nagagogulan/node1:latest
          nagagogulan/node1:v${{ github.run_number }}

    - name: Set Docker image version as an environment variable
      run: echo "DOCKER_IMAGE_VERSION=v${{ github.run_number }}" >> $GITHUB_ENV

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Use Docker image version in deployment
      run: |
        echo "Deploying Docker image version $DOCKER_IMAGE_VERSION"
        # Your deployment steps here using the version environment variable
