name: Build, Push, and Delete Old Docker Images

on:
  push:
    branches:
      - main

jobs:
  build_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: nagagogulan
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image with a unique version tag
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: .github/workflows
        push: true
        tags: |
          nagagogulan/node1:v${{ github.run_number }}


  delete-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete Docker Image
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          # Authenticate with Docker Hub
          echo $DOCKERHUB_TOKEN | docker login -u nagagogulan --password: ${{ secrets.DOCKER_PASSWORD }}

          # Delete the specific Docker image
          docker manifest inspect nagagogulan/node1:120 && docker push --delete nagagogulan/node1:120
