name: Node.js CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version:
          - '14'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Set up environment variables
      run: echo "${{ secrets.PROD_ENV_FILE }}" > .env

    # Add your additional steps for testing, building, or deploying here
